### ISSUE TITLE
core architecture can be optimized by chatGPT

### ISSUE THREAD

**Issue by NaturelLee** [farm-fe/rfcs#4]
free chatGPT list: https://github.com/xx025/carrot

**Comment by wre232114** [comment]
What's the meaning of "optimized by chatGPT", does it mean using chartGPT to design a better one

**Comment by NaturelLee** [comment]
Only the doc, correct errors and make the doc bettter.

here is the example:
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/12494855/224765867-b29d1013-79b4-4755-b0df-244e1efe7e54.png">

**Comment by NaturelLee** [comment]
并不是所有的经过chatGPT处理过的文档都符合要求。不过可以在时间允许的情况下尝试使用它来检查、优化、润色。

**Comment by wre232114** [comment]
了解了，感谢建议
